
storage:

  # This section should not be modified unless there is a strong need. Please contact
  # the repository maintainers if you feel you need to use different settings here –
  # there may be another way to accomplish what you need.
  classname:  ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: ${ROOT_DIR}
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      csv:
        file_pattern: '.*\.csv'
        classname: ingest.bbd.pipeline.filehandler.CustomFileHandler #tsdat.io.filehandlers.CsvHandler
        parameters:
          read:
            read_csv:
              sep: ","
              header: 0
              index_col: False

    # The output section should not be modified unless there is a strong need. Please
    # contact the repository maintainers if you feel you need to write to a different
    # format.
    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.NetCdfHandler

#      csv:
#        file_extension: ".csv"
#        classname: tsdat.io.filehandlers.CsvHandler

